// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: api/proto/analytic.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID        string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Login       string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Timestamp   int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Emails      []string `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	UUIDMessage string   `protobuf:"bytes,5,opt,name=UUIDMessage,proto3" json:"UUIDMessage,omitempty"`
}

func (x *AddTaskRequest) Reset() {
	*x = AddTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_analytic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskRequest) ProtoMessage() {}

func (x *AddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskRequest.ProtoReflect.Descriptor instead.
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytic_proto_rawDescGZIP(), []int{0}
}

func (x *AddTaskRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *AddTaskRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddTaskRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AddTaskRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *AddTaskRequest) GetUUIDMessage() string {
	if x != nil {
		return x.UUIDMessage
	}
	return ""
}

type ActionTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID        string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Timestamp   int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Action      string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Value       bool   `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	UUIDMessage string `protobuf:"bytes,6,opt,name=UUIDMessage,proto3" json:"UUIDMessage,omitempty"`
}

func (x *ActionTaskRequest) Reset() {
	*x = ActionTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_analytic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionTaskRequest) ProtoMessage() {}

func (x *ActionTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionTaskRequest.ProtoReflect.Descriptor instead.
func (*ActionTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytic_proto_rawDescGZIP(), []int{1}
}

func (x *ActionTaskRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ActionTaskRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ActionTaskRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActionTaskRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionTaskRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *ActionTaskRequest) GetUUIDMessage() string {
	if x != nil {
		return x.UUIDMessage
	}
	return ""
}

type AnalyticResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AnalyticResponse) Reset() {
	*x = AnalyticResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_analytic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticResponse) ProtoMessage() {}

func (x *AnalyticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticResponse.ProtoReflect.Descriptor instead.
func (*AnalyticResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytic_proto_rawDescGZIP(), []int{2}
}

var File_api_proto_analytic_proto protoreflect.FileDescriptor

var file_api_proto_analytic_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22,
	0x92, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x55, 0x49, 0x44, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55, 0x55, 0x49, 0x44, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x55, 0x55, 0x49, 0x44, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55, 0x55, 0x49, 0x44, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x82, 0x01, 0x0a, 0x08, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x74, 0x69, 0x63, 0x12, 0x37, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_analytic_proto_rawDescOnce sync.Once
	file_api_proto_analytic_proto_rawDescData = file_api_proto_analytic_proto_rawDesc
)

func file_api_proto_analytic_proto_rawDescGZIP() []byte {
	file_api_proto_analytic_proto_rawDescOnce.Do(func() {
		file_api_proto_analytic_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_analytic_proto_rawDescData)
	})
	return file_api_proto_analytic_proto_rawDescData
}

var file_api_proto_analytic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_analytic_proto_goTypes = []interface{}{
	(*AddTaskRequest)(nil),    // 0: api.AddTaskRequest
	(*ActionTaskRequest)(nil), // 1: api.ActionTaskRequest
	(*AnalyticResponse)(nil),  // 2: api.AnalyticResponse
}
var file_api_proto_analytic_proto_depIdxs = []int32{
	0, // 0: api.Analytic.AddTask:input_type -> api.AddTaskRequest
	1, // 1: api.Analytic.ActionTask:input_type -> api.ActionTaskRequest
	2, // 2: api.Analytic.AddTask:output_type -> api.AnalyticResponse
	2, // 3: api.Analytic.ActionTask:output_type -> api.AnalyticResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_analytic_proto_init() }
func file_api_proto_analytic_proto_init() {
	if File_api_proto_analytic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_analytic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_analytic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_analytic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyticResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_analytic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytic_proto_goTypes,
		DependencyIndexes: file_api_proto_analytic_proto_depIdxs,
		MessageInfos:      file_api_proto_analytic_proto_msgTypes,
	}.Build()
	File_api_proto_analytic_proto = out.File
	file_api_proto_analytic_proto_rawDesc = nil
	file_api_proto_analytic_proto_goTypes = nil
	file_api_proto_analytic_proto_depIdxs = nil
}
